Final form for secret hitler
open-boardgame-stats/webapp pull request #13
Opened 2020-10-27 17:19 UTC by sesh92

2020-10-28 21:35 UTC, maksimf reviewed
I left my comments

2020-10-28 21:35 UTC, maksimf commented on src/pages/games/secret-hitler/Form.tsx
> +}
What's invalid about that?

2020-10-28 21:49 UTC, MOZGIII commented on src/pages/games/secret-hitler/Form.tsx
> +}
`const a = <qwe />` is just not a component, it's an evaluated `React.Node` or sth like that.

Using `const a: React.FC = ...` would immediately attract the attention to this.
Proper form (without type annotation, which is recommended) is `const a = () => <qwe>`.

2020-11-07 13:42 UTC, MOZGIII requested changes
I've submitted some change requests before

2020-11-07 13:56 UTC, sesh92 commented on src/pages/games/secret-hitler/Form.tsx
> +}
fixed

2020-11-07 13:58 UTC, maksimf approved these changes

2020-11-07 22:56 UTC, MOZGIII commented on src/pages/games/secret-hitler/Form/PlayerRow.tsx
> +      </TextField>
Text fields are jumping around when hint shows/hides

2020-11-07 23:03 UTC, MOZGIII commented on src/pages/games/secret-hitler/Form/index.tsx
> +  const { initialValues } = props;
Instead of using the wrapper component, use the default values instead: https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#deprecate-defaultprops-on-function-components.

```suggestion
const FormComponent: React.FC<SHFormProps> = ({ initialValues = initialValues }) => {
```

2020-11-09 16:27 UTC, MOZGIII commented on src/pages/games/secret-hitler/Form/index.tsx
> +  const { initialValues } = props;
Oh my, it broke things spectacularly.

2020-11-09 16:59 UTC, sesh92 commented on src/pages/games/secret-hitler/Form/PlayerRow.tsx
> +      </TextField>
fixed

2020-11-09 17:07 UTC, sesh92 commented on src/pages/games/secret-hitler/Form/index.tsx
> +  const { initialValues } = props;
reject changes

2020-11-09 17:14 UTC, flungloaf approved these changes

2020-11-09 19:08 UTC, MOZGIII commented on src/pages/games/secret-hitler/Form/index.tsx
> +  const { initialValues } = props;
This is easy to fix from within a proper editor environment, with the same core idea.

2020-11-09 20:28 UTC, sesh92 commented on src/pages/games/secret-hitler/Form/index.tsx
> +  const { initialValues } = props;
what's problem?

2020-11-10 10:30 UTC, MOZGIII approved these changes

2020-11-10 10:50 UTC, merged